/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.year2018.ndk.jniNative.swig.plus;

public enum JEnum {
  J_ONE(PlusJNI.J_ONE_get()),
  J_TWO(PlusJNI.J_TWO_get()),
  J_THREE,
  J_FOUR;

  public final int swigValue() {
    return swigValue;
  }

  public static JEnum swigToEnum(int swigValue) {
    JEnum[] swigValues = JEnum.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (JEnum swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + JEnum.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private JEnum() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private JEnum(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private JEnum(JEnum swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

