/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.year2018.ndk.jniNative.swig.plus;

public class Plus implements PlusConstants {
  public static long getuid() throws java.lang.IllegalAccessException {
    return PlusJNI.getuid();
  }

  public static void setCounter(int value) {
    PlusJNI.counter_set(value);
  }

  public static int getCounter() {
    return PlusJNI.counter_get();
  }

  public static int getReadOnly() {
    return PlusJNI.readOnly_get();
  }

  public static void setReadWrite(int value) {
    PlusJNI.readWrite_set(value);
  }

  public static int getReadWrite() {
    return PlusJNI.readWrite_get();
  }

  public static void defaultValueFunc(int a, int b, int c) {
    PlusJNI.defaultValueFunc__SWIG_0(a, b, c);
  }

  public static void defaultValueFunc(int a, int b) {
    PlusJNI.defaultValueFunc__SWIG_1(a, b);
  }

  public static void defaultValueFunc(int a) {
    PlusJNI.defaultValueFunc__SWIG_2(a);
  }

  public static void defaultValueFunc() {
    PlusJNI.defaultValueFunc__SWIG_3();
  }

  public static void overloadFunc(double d) {
    PlusJNI.overloadFunc__SWIG_0(d);
  }

  public static void overloadFunc(int i) {
    PlusJNI.overloadFunc__SWIG_1(i);
  }

}
