/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.year2018.ndk.jniNative.swig.plus;

public interface PlusConstants {
  public final static int MAX_WIDTH = 640;
  public final static int MAX_HEIGHT = PlusJNI.MAX_HEIGHT_get();
  public final static int E_ONE = PlusJNI.E_ONE_get();
  public final static int E_TWO = PlusJNI.E_TWO_get();
  public final static int E_THREE = PlusJNI.E_THREE_get();
  public final static int E_FOUR = PlusJNI.E_FOUR_get();

}
