/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.year2018.ndk.jniNative.swig.plus;

public class PlusJNI {
  public final static native long getuid() throws java.lang.IllegalAccessException;
  public final static native void counter_set(int jarg1);
  public final static native int counter_get();
  public final static native int MAX_HEIGHT_get();
  public final static native int readOnly_get();
  public final static native void readWrite_set(int jarg1);
  public final static native int readWrite_get();
  public final static native int E_ONE_get();
  public final static native int E_TWO_get();
  public final static native int E_THREE_get();
  public final static native int E_FOUR_get();
  public final static native int S_ONE_get();
  public final static native int S_TWO_get();
  public final static native int U_ONE_get();
  public final static native int U_TWO_get();
  public final static native int U_THREE_get();
  public final static native int U_FOUR_get();
  public final static native int J_ONE_get();
  public final static native int J_TWO_get();
  public final static native void Point_x_set(long jarg1, Point jarg1_, int jarg2);
  public final static native int Point_x_get(long jarg1, Point jarg1_);
  public final static native void Point_y_set(long jarg1, Point jarg1_, int jarg2);
  public final static native int Point_y_get(long jarg1, Point jarg1_);
  public final static native long new_Point();
  public final static native void delete_Point(long jarg1);
  public final static native void defaultValueFunc__SWIG_0(int jarg1, int jarg2, int jarg3);
  public final static native void defaultValueFunc__SWIG_1(int jarg1, int jarg2);
  public final static native void defaultValueFunc__SWIG_2(int jarg1);
  public final static native void defaultValueFunc__SWIG_3();
  public final static native void overloadFunc__SWIG_0(double jarg1);
  public final static native void overloadFunc__SWIG_1(int jarg1);
  public final static native long new_A__SWIG_0();
  public final static native long new_A__SWIG_1(int jarg1);
  public final static native void delete_A(long jarg1);
  public final static native void A_print(long jarg1, A jarg1_);
  public final static native void A_value_set(long jarg1, A jarg1_, int jarg2);
  public final static native int A_value_get(long jarg1, A jarg1_);
}
