/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.year2018.ndk.jniNative.swig.plus;

public final class Safe {
  public final static Safe S_ONE = new Safe("S_ONE", PlusJNI.S_ONE_get());
  public final static Safe S_TWO = new Safe("S_TWO", PlusJNI.S_TWO_get());
  public final static Safe S_THREE = new Safe("S_THREE");
  public final static Safe S_FOUR = new Safe("S_FOUR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Safe swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Safe.class + " with value " + swigValue);
  }

  private Safe(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Safe(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Safe(String swigName, Safe swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Safe[] swigValues = { S_ONE, S_TWO, S_THREE, S_FOUR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

