/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.year2018.ndk.jniNative.swig.plus;

public final class Unsafe {
  public final static int U_ONE = PlusJNI.U_ONE_get();
  public final static int U_TWO = PlusJNI.U_TWO_get();
  public final static int U_THREE = PlusJNI.U_THREE_get();
  public final static int U_FOUR = PlusJNI.U_FOUR_get();
}

