/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.year2018.ndk.jniNative.swig.c2j;

public class AsyncUidProvider {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AsyncUidProvider(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AsyncUidProvider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        C2JJNI.delete_AsyncUidProvider(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AsyncUidProvider() {
    this(C2JJNI.new_AsyncUidProvider(), true);
  }

  public void get() {
    C2JJNI.AsyncUidProvider_get(swigCPtr, this);
  }

  public void onUid(long uid) {
    C2JJNI.AsyncUidProvider_onUid(swigCPtr, this, uid);
  }

}
