/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_year2018_ndk_activity_wav_WavActivity_PlayTask */

#ifndef _Included_com_year2018_ndk_activity_wav_WavActivity_PlayTask
#define _Included_com_year2018_ndk_activity_wav_WavActivity_PlayTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
