/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_year2018_ndk_activity_socket_EchoClientActivity */

#ifndef _Included_com_year2018_ndk_activity_socket_EchoClientActivity
#define _Included_com_year2018_ndk_activity_socket_EchoClientActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_year2018_ndk_activity_socket_EchoClientActivity
 * Method:    nativeStartTcpClient
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_year2018_ndk_activity_socket_EchoClientActivity_nativeStartTcpClient
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     com_year2018_ndk_activity_socket_EchoClientActivity
 * Method:    nativeStartUdpClient
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_year2018_ndk_activity_socket_EchoClientActivity_nativeStartUdpClient
  (JNIEnv *, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
