/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_year2018_ndk_activity_socket_EchoLocalActivity */

#ifndef _Included_com_year2018_ndk_activity_socket_EchoLocalActivity
#define _Included_com_year2018_ndk_activity_socket_EchoLocalActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_year2018_ndk_activity_socket_EchoLocalActivity
 * Method:    nativeStartLocalServer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_year2018_ndk_activity_socket_EchoLocalActivity_nativeStartLocalServer
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
