/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.year2018.ndk.jniNative.swig.web;

public class ClassFactory {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ClassFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClassFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ShapeJNI.delete_ClassFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IShapeProvider newInstance(SWIGTYPE_p_std__string class_name) {
    long cPtr = ShapeJNI.ClassFactory_newInstance(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(class_name));
    return (cPtr == 0) ? null : new IShapeProvider(cPtr, false);
  }

  public void releaseClass(IShapeProvider shape_provider) {
    ShapeJNI.ClassFactory_releaseClass(swigCPtr, this, IShapeProvider.getCPtr(shape_provider), shape_provider);
  }

  public ClassFactory() {
    this(ShapeJNI.new_ClassFactory(), true);
  }

}
