/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.year2018.ndk.jniNative.swig.web;

public class ShapeJNI {
  public final static native void IShapeProvider_openFile(long jarg1, IShapeProvider jarg1_, long jarg2);
  public final static native void IShapeProvider_extent(long jarg1, IShapeProvider jarg1_, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native long IShapeProvider_toJavaString(long jarg1, IShapeProvider jarg1_);
  public final static native void delete_IShapeProvider(long jarg1);
  public final static native long ClassFactory_newInstance(long jarg1, ClassFactory jarg1_, long jarg2);
  public final static native void ClassFactory_releaseClass(long jarg1, ClassFactory jarg1_, long jarg2, IShapeProvider jarg2_);
  public final static native long new_ClassFactory();
  public final static native void delete_ClassFactory(long jarg1);
}
