/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_year2018_ndk_jniNative_Imooc */

#ifndef _Included_com_year2018_ndk_jniNative_Imooc
#define _Included_com_year2018_ndk_jniNative_Imooc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_year2018_ndk_jniNative_Imooc
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_year2018_ndk_jniNative_Imooc_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_year2018_ndk_jniNative_Imooc
 * Method:    callStaticMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_year2018_ndk_jniNative_Imooc_callStaticMethod__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_year2018_ndk_jniNative_Imooc
 * Method:    callStaticMethod
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_year2018_ndk_jniNative_Imooc_callStaticMethod__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_year2018_ndk_jniNative_Imooc
 * Method:    callInstanceMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_year2018_ndk_jniNative_Imooc_callInstanceMethod__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_year2018_ndk_jniNative_Imooc
 * Method:    callInstanceMethod
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_year2018_ndk_jniNative_Imooc_callInstanceMethod__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
