/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_year2018_ndk_jniNative_General */

#ifndef _Included_com_year2018_ndk_jniNative_General
#define _Included_com_year2018_ndk_jniNative_General
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_year2018_ndk_jniNative_General
 * Method:    getPkgName
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_year2018_ndk_jniNative_General_getPkgName
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
